import { useCallback, useEffect, useMemo, useState } from 'react';
import { api } from '../../../shared/api';
import { formatDate, formatUsd } from '../../../shared/money';
import { useI18n, type MessageKey, type TranslateFn } from '../../../shared/i18n';
import { useNavigation, useRoute } from '../../../shared/routing';
import {
  PARCEL_TONE,
  addressLines,
  estimatedTaxMinor,
  parcelConditionLabel,
  parcelStatusLabel,
  taxRateLabel,
  type InboundAddress,
  type ParcelSummary,
  type ParcelWorkflow,
} from '../../../shared/parcels';
import {
  Button,
  ContextTabs,
  DetailRow,
  EmptyState,
  ErrorState,
  Field,
  MetricCard,
  Panel,
  SkeletonTable,
  StatusBadge,
  SuccessNote,
  TabPanel,
} from '../../../shared/ui/primitives';
import { DetailDrawer } from '../../../shared/ui/DetailDrawer';
import {
  IconAlert,
  IconBox,
  IconCheck,
  IconClock,
  IconInbox,
  IconLocation,
  IconPlus,
} from '../../../shared/ui/icons';

/**
 * Inbound — where a collector's purchases arrive.
 *
 * This is the half of the product that did not exist. Before it, an item was in
 * a vault because a warehouse operator typed it in; there was no address to ship
 * to, nothing to watch on its way, and no record of a parcel at all.
 *
 * Three tabs, in the order somebody actually needs them: the addresses to paste
 * into a checkout, the parcels those purchases become, and how busy the
 * warehouse currently is.
 */
const TABS = ['addresses', 'parcels', 'processing'] as const;
type InboundTab = (typeof TABS)[number];

export function InboundPage() {
  const { t } = useI18n();
  const route = useRoute();
  const { goTab, openRecord, closeRecord } = useNavigation(route);

  const [status, setStatus] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [parcels, setParcels] = useState<ParcelSummary[] | null>(null);

  const tab: InboundTab = (TABS as readonly string[]).includes(route.tab ?? '')
    ? (route.tab as InboundTab)
    : 'addresses';

  const loadParcels = useCallback(async () => {
    try {
      setParcels(await api.get<ParcelSummary[]>('/me/parcels'));
      setError(null);
    } catch (e) {
      setError((e as Error).message);
      setParcels([]);
    }
  }, []);

  useEffect(() => {
    void loadParcels();
  }, [loadParcels]);

  const tabs = TABS.map((key) => ({ key, label: t(`inbound.tab.${key}` as MessageKey) }));

  return (
    <>
      <ContextTabs label={t('inbound.title')} tabs={tabs} active={tab} onSelect={goTab} />

      {status && <SuccessNote>{status}</SuccessNote>}
      {error && <ErrorState message={error} onRetry={() => void loadParcels()} retryLabel={t('ui.retry')} />}

      {tab === 'addresses' && (
        <TabPanel tab="addresses">
          <AddressesTab onError={setError} />
        </TabPanel>
      )}

      {tab === 'parcels' && (
        <TabPanel tab="parcels">
          <ParcelsTab
            parcels={parcels}
            openId={route.params.parcel ?? null}
            onOpen={(id) => openRecord('parcel', id)}
            onClose={() => closeRecord('parcel')}
            onChanged={async (message) => {
              setStatus(message);
              await loadParcels();
            }}
            onError={setError}
          />
        </TabPanel>
      )}

      {tab === 'processing' && (
        <TabPanel tab="processing">
          <ProcessingTab onError={setError} />
        </TabPanel>
      )}
    </>
  );
}

/* ============================================================
   Addresses
   ============================================================ */

/** A worked example, so the tax comparison is a number and not a percentage. */
const EXAMPLE_PURCHASE_MINOR = 50_000; // $500

/**
 * The addresses a collector ships purchases to.
 *
 * The `C/O` line is generated by the API from the account's own username and is
 * shown as the first line of the block, because it is the one part a seller
 * cannot guess and the one part that makes a parcel findable. Everything here is
 * copyable as a unit — a person pasting an address into a checkout should not be
 * assembling it from four separate fields.
 */
function AddressesTab({ onError }: { onError: (m: string) => void }) {
  const { t } = useI18n();
  const [addresses, setAddresses] = useState<InboundAddress[] | null>(null);
  const [copied, setCopied] = useState<string | null>(null);

  useEffect(() => {
    void (async () => {
      try {
        setAddresses(await api.get<InboundAddress[]>('/me/inbound-addresses'));
      } catch (e) {
        onError((e as Error).message);
        setAddresses([]);
      }
    })();
  }, [onError]);

  async function copy(address: InboundAddress) {
    const text = addressLines(address).join('\n');
    try {
      await navigator.clipboard.writeText(text);
      setCopied(address.code);
      window.setTimeout(() => setCopied(null), 2000);
    } catch {
      // Clipboard permission can be refused; the address is on screen either way.
      onError(t('inbound.address.copyFailed'));
    }
  }

  if (addresses === null) return <SkeletonTable rows={2} columns={2} />;
  if (addresses.length === 0) {
    return (
      <Panel title={t('inbound.address.title')} flush>
        <EmptyState
          title={t('inbound.address.none')}
          text={t('inbound.address.noneText')}
          icon={<IconLocation />}
        />
      </Panel>
    );
  }

  const primary = addresses.find((a) => a.role === 'primary');
  const forwarding = addresses.find((a) => a.role === 'forwarding');
  const taxSaved =
    primary && forwarding
      ? estimatedTaxMinor(EXAMPLE_PURCHASE_MINOR, primary.salesTaxBps) -
        estimatedTaxMinor(EXAMPLE_PURCHASE_MINOR, forwarding.salesTaxBps)
      : 0;

  return (
    <>
      <Panel title={t('inbound.address.title')} subtitle={t('inbound.address.subtitle')}>
        <ul className="card-grid">
          {addresses.map((address) => (
            <li key={address.code} className="card">
              <div className="card-meta">
                <h3 className="card-title" style={{ flex: '1 1 auto' }}>
                  {address.name}
                </h3>
                <StatusBadge tone={address.role === 'primary' ? 'gold' : 'info'}>
                  {t(
                    address.role === 'primary'
                      ? 'inbound.address.rolePrimary'
                      : 'inbound.address.roleForwarding',
                  )}
                </StatusBadge>
              </div>

              {/* dir=ltr unconditionally: a US postal address is left-to-right
                  even when the surrounding page is Hebrew, and a mirrored one
                  is not deliverable. */}
              <pre className="address-block" dir="ltr">
                {addressLines(address).join('\n')}
              </pre>

              <dl className="detail-list">
                <DetailRow label={t('inbound.address.salesTax')}>
                  {address.salesTaxBps === 0 ? (
                    <StatusBadge tone="success">{t('inbound.address.noSalesTax')}</StatusBadge>
                  ) : (
                    <span dir="ltr">{taxRateLabel(address.salesTaxBps)}</span>
                  )}
                </DetailRow>
                {address.role === 'forwarding' && address.forwardingDays != null && (
                  <DetailRow label={t('inbound.address.transit')}>
                    {t('inbound.address.transitDays', { days: address.forwardingDays })}
                  </DetailRow>
                )}
              </dl>

              <div className="actions">
                <Button
                  size="sm"
                  variant={copied === address.code ? 'secondary' : 'gold'}
                  icon={copied === address.code ? <IconCheck /> : undefined}
                  onClick={() => void copy(address)}
                >
                  {t(copied === address.code ? 'inbound.address.copied' : 'inbound.address.copy')}
                </Button>
              </div>
            </li>
          ))}
        </ul>
      </Panel>

      {primary && forwarding && (
        <Panel title={t('inbound.guidance.title')} subtitle={t('inbound.guidance.subtitle')}>
          <div className="stack stack--tight">
            <p>
              {t('inbound.guidance.body', {
                primary: primary.name,
                primaryRate: taxRateLabel(primary.salesTaxBps),
                forwarding: forwarding.name,
                days: forwarding.forwardingDays ?? 0,
              })}
            </p>
            {/* A number, not a rate. "6.625%" is arithmetic homework; "$33.13 on
                a $500 card" is the decision the collector is actually making. */}
            <p className="field-hint">
              {t('inbound.guidance.example', {
                amount: formatUsd(EXAMPLE_PURCHASE_MINOR),
                saved: formatUsd(taxSaved),
              })}
            </p>
            <p className="field-hint">{t('inbound.guidance.caveat')}</p>
          </div>
        </Panel>
      )}
    </>
  );
}

/* ============================================================
   Parcels
   ============================================================ */

function ParcelsTab({
  parcels,
  openId,
  onOpen,
  onClose,
  onChanged,
  onError,
}: {
  parcels: ParcelSummary[] | null;
  openId: string | null;
  onOpen: (id: string) => void;
  onClose: () => void;
  onChanged: (message: string) => Promise<void>;
  onError: (m: string) => void;
}) {
  const { t, locale } = useI18n();
  const selected = useMemo(
    () => (parcels ?? []).find((p) => p.id === openId) ?? null,
    [parcels, openId],
  );

  return (
    <>
      <RegisterParcelForm onRegistered={onChanged} onError={onError} />

      <Panel title={t('inbound.parcels.title')} subtitle={t('inbound.parcels.subtitle')} flush>
        {parcels === null ? (
          <SkeletonTable rows={4} columns={5} />
        ) : parcels.length === 0 ? (
          <EmptyState
            title={t('inbound.parcels.empty')}
            text={t('inbound.parcels.emptyText')}
            icon={<IconInbox />}
          />
        ) : (
          <div className="dt-wrap dt-wrap--stack">
            <table className="data-table">
              <caption>{t('inbound.parcels.title')}</caption>
              <thead>
                <tr>
                  <th scope="col">{t('inbound.parcels.col.parcel')}</th>
                  <th scope="col">{t('inbound.parcels.col.tracking')}</th>
                  <th scope="col">{t('inbound.parcels.col.where')}</th>
                  <th scope="col">{t('inbound.parcels.col.status')}</th>
                  <th scope="col">{t('inbound.parcels.col.updated')}</th>
                  <th scope="col" className="td-tight" />
                </tr>
              </thead>
              <tbody>
                {parcels.map((p) => (
                  <tr
                    key={p.id}
                    className={'is-clickable' + (p.id === openId ? ' is-selected' : '')}
                    tabIndex={0}
                    onClick={() => onOpen(p.id)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' || e.key === ' ') {
                        e.preventDefault();
                        onOpen(p.id);
                      }
                    }}
                  >
                    <td data-label={t('inbound.parcels.col.parcel')} className="dt-primary">
                      {p.declaredContents || t('inbound.parcels.undeclared')}
                      <span className="dt-sub" dir="ltr">
                        {p.code}
                      </span>
                    </td>
                    <td data-label={t('inbound.parcels.col.tracking')} dir="ltr">
                      {p.trackingNumber ? <code>{p.trackingNumber}</code> : <span className="muted">—</span>}
                      {p.carrier && <span className="dt-sub">{p.carrier}</span>}
                    </td>
                    <td data-label={t('inbound.parcels.col.where')}>
                      {p.facilityName ?? '—'}
                      {p.forwardedAt && (
                        <span className="dt-sub">{t('inbound.parcels.forwarded')}</span>
                      )}
                    </td>
                    <td data-label={t('inbound.parcels.col.status')}>
                      <StatusBadge tone={PARCEL_TONE[p.status] ?? 'neutral'}>
                        {parcelStatusLabel(t, p.status)}
                      </StatusBadge>
                    </td>
                    <td data-label={t('inbound.parcels.col.updated')} dir="ltr">
                      {formatDate(
                        p.processedAt ?? p.openedAt ?? p.receivedAt ?? p.expectedAt ?? '',
                        locale,
                      ) || '—'}
                    </td>
                    <td className="td-tight">
                      <Button
                        size="sm"
                        variant="secondary"
                        onClick={(e) => {
                          e.stopPropagation();
                          onOpen(p.id);
                        }}
                      >
                        {t('ss.tracking.details')}
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Panel>

      {selected && (
        <ParcelDrawer
          parcel={selected}
          t={t}
          locale={locale}
          onClose={onClose}
          onChanged={onChanged}
          onError={onError}
        />
      )}
    </>
  );
}

/**
 * Tell Bault a parcel is coming.
 *
 * Entirely optional — an unannounced parcel is received the same way. What
 * registering buys is that the collector can watch it, and that the operator who
 * receives it has a tracking number to match against, which turns an anonymous
 * box into somebody's property before anyone opens it.
 */
function RegisterParcelForm({
  onRegistered,
  onError,
}: {
  onRegistered: (message: string) => Promise<void>;
  onError: (m: string) => void;
}) {
  const { t } = useI18n();
  const [addresses, setAddresses] = useState<InboundAddress[]>([]);
  const [facilityCode, setFacilityCode] = useState('');
  const [carrier, setCarrier] = useState('');
  const [trackingNumber, setTrackingNumber] = useState('');
  const [declaredContents, setDeclaredContents] = useState('');
  const [internationalOrigin, setInternationalOrigin] = useState(false);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    void (async () => {
      try {
        const list = await api.get<InboundAddress[]>('/me/inbound-addresses');
        setAddresses(list);
        const preferred = list.find((a) => a.role === 'primary') ?? list[0];
        if (preferred) setFacilityCode(preferred.code);
      } catch (e) {
        onError((e as Error).message);
      }
    })();
  }, [onError]);

  async function submit() {
    setBusy(true);
    try {
      const created = await api.post<{ code: string }>('/me/parcels', {
        facilityCode,
        carrier: carrier.trim() || undefined,
        trackingNumber: trackingNumber.trim() || undefined,
        declaredContents: declaredContents.trim() || undefined,
        internationalOrigin,
      });
      setCarrier('');
      setTrackingNumber('');
      setDeclaredContents('');
      setInternationalOrigin(false);
      await onRegistered(t('inbound.register.done', { code: created.code }));
    } catch (e) {
      onError((e as Error).message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <Panel title={t('inbound.register.title')} subtitle={t('inbound.register.subtitle')}>
      <div className="stack stack--tight" style={{ maxWidth: 560 }}>
        <div className="form-grid">
          <label className="field">
            <span className="field-label">{t('inbound.register.facility')}</span>
            <select value={facilityCode} onChange={(e) => setFacilityCode(e.target.value)}>
              {addresses.map((a) => (
                <option key={a.code} value={a.code}>
                  {a.name}
                </option>
              ))}
            </select>
          </label>
          <label className="field">
            <span className="field-label">{t('inbound.register.carrier')}</span>
            <input value={carrier} onChange={(e) => setCarrier(e.target.value)} />
          </label>
          <Field label={t('inbound.register.tracking')} hint={t('inbound.register.trackingHint')}>
            <input value={trackingNumber} onChange={(e) => setTrackingNumber(e.target.value)} dir="ltr" />
          </Field>
          <label className="field">
            <span className="field-label">{t('inbound.register.contents')}</span>
            <input value={declaredContents} onChange={(e) => setDeclaredContents(e.target.value)} />
          </label>
        </div>

        <label className="check">
          <input
            type="checkbox"
            checked={internationalOrigin}
            onChange={(e) => setInternationalOrigin(e.target.checked)}
          />
          {t('inbound.register.international')}
        </label>
        {internationalOrigin && (
          <p className="field-hint">{t('inbound.register.internationalHint')}</p>
        )}

        <div className="row">
          <Button variant="gold" icon={<IconPlus />} disabled={busy || !facilityCode} onClick={() => void submit()}>
            {t('inbound.register.submit')}
          </Button>
        </div>
      </div>
    </Panel>
  );
}

function ParcelDrawer({
  parcel,
  t,
  locale,
  onClose,
  onChanged,
  onError,
}: {
  parcel: ParcelSummary;
  t: TranslateFn;
  locale: string;
  onClose: () => void;
  onChanged: (message: string) => Promise<void>;
  onError: (m: string) => void;
}) {
  const [busy, setBusy] = useState(false);

  async function cancel() {
    setBusy(true);
    try {
      await api.post(`/me/parcels/${parcel.id}/cancel`);
      await onChanged(t('inbound.parcel.cancelled', { code: parcel.code }));
      onClose();
    } catch (e) {
      onError((e as Error).message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <DetailDrawer
      title={parcel.code}
      subtitle={parcelStatusLabel(t, parcel.status)}
      onClose={onClose}
      footer={
        <>
          {/* Only ever offered before anything physical exists. Once a box is on
              a shelf no customer action can make the record of it go away. */}
          {parcel.status === 'expected' && (
            <Button variant="danger" disabled={busy} onClick={() => void cancel()}>
              {t('inbound.parcel.cancel')}
            </Button>
          )}
          <Button variant="ghost" onClick={onClose}>
            {t('ui.close')}
          </Button>
        </>
      }
    >
      <dl className="detail-list">
        <DetailRow label={t('inbound.parcels.col.status')}>
          <StatusBadge tone={PARCEL_TONE[parcel.status] ?? 'neutral'}>
            {parcelStatusLabel(t, parcel.status)}
          </StatusBadge>
        </DetailRow>
        <DetailRow label={t('inbound.parcels.col.where')}>{parcel.facilityName ?? '—'}</DetailRow>
        <DetailRow label={t('inbound.register.contents')}>
          {parcel.declaredContents || t('inbound.parcels.undeclared')}
        </DetailRow>
        <DetailRow label={t('inbound.parcels.col.tracking')}>
          {parcel.trackingNumber ? <code dir="ltr">{parcel.trackingNumber}</code> : '—'}
        </DetailRow>
        <DetailRow label={t('inbound.register.carrier')}>{parcel.carrier ?? '—'}</DetailRow>
        {parcel.internationalOrigin && (
          <DetailRow label={t('inbound.parcel.origin')}>
            <StatusBadge tone="warning">{t('inbound.parcel.international')}</StatusBadge>
          </DetailRow>
        )}
        {parcel.receivedAt && (
          <DetailRow label={t('inbound.parcel.receivedAt')}>
            <span dir="ltr">{formatDate(parcel.receivedAt, locale)}</span>
          </DetailRow>
        )}
        {parcel.forwardedAt && (
          <DetailRow label={t('inbound.parcel.forwardedAt')}>
            <span dir="ltr">{formatDate(parcel.forwardedAt, locale)}</span>
          </DetailRow>
        )}
        {parcel.openedAt && (
          <DetailRow label={t('inbound.parcel.openedAt')}>
            <span dir="ltr">{formatDate(parcel.openedAt, locale)}</span>
          </DetailRow>
        )}
        {parcel.processedAt && (
          <DetailRow label={t('inbound.parcel.processedAt')}>
            <span dir="ltr">{formatDate(parcel.processedAt, locale)}</span>
          </DetailRow>
        )}
        {parcel.condition && (
          <DetailRow label={t('inbound.parcel.condition')}>
            <StatusBadge tone={parcel.condition === 'sound' ? 'success' : 'error'}>
              {parcelConditionLabel(t, parcel.condition)}
            </StatusBadge>
            {parcel.conditionNotes && <span className="detail-value-sub">{parcel.conditionNotes}</span>}
          </DetailRow>
        )}
      </dl>
    </DetailDrawer>
  );
}

/* ============================================================
   Processing backlog
   ============================================================ */

/**
 * How busy the warehouse is right now.
 *
 * Every figure is derived from what is actually on the bench — the counts are a
 * live query and the wait is the age of the oldest unprocessed arrival. There is
 * deliberately no published turnaround target: a number typed into a page is a
 * promise nobody measured, and this section exists precisely so a collector can
 * see the real answer instead of being given one.
 */
function ProcessingTab({ onError }: { onError: (m: string) => void }) {
  const { t, locale } = useI18n();
  const [workflow, setWorkflow] = useState<ParcelWorkflow | null>(null);

  const load = useCallback(async () => {
    try {
      setWorkflow(await api.get<ParcelWorkflow>('/parcels/workflow/status'));
    } catch (e) {
      onError((e as Error).message);
    }
  }, [onError]);

  useEffect(() => {
    void load();
  }, [load]);

  return (
    <>
      <div className="metric-grid">
        <MetricCard
          label={t('inbound.workflow.awaitingOpen')}
          value={workflow?.awaitingOpen ?? '—'}
          icon={<IconBox />}
          tone="blue"
          footer={t('inbound.workflow.awaitingOpenNote')}
        />
        <MetricCard
          label={t('inbound.workflow.awaitingProcessing')}
          value={workflow?.awaitingProcessing ?? '—'}
          icon={<IconClock />}
          tone="amber"
          footer={t('inbound.workflow.awaitingProcessingNote')}
        />
        <MetricCard
          label={t('inbound.workflow.oldest')}
          value={
            workflow?.oldestWaitingHours == null
              ? '—'
              : t('inbound.workflow.hours', { hours: workflow.oldestWaitingHours })
          }
          icon={<IconAlert />}
          tone="violet"
          footer={
            workflow?.oldestReceivedAt
              ? t('inbound.workflow.since', {
                  date: formatDate(workflow.oldestReceivedAt, locale),
                })
              : t('inbound.workflow.oldestNote')
          }
        />
      </div>

      <Panel title={t('inbound.workflow.title')} subtitle={t('inbound.workflow.subtitle')}>
        <p className="field-hint">{t('inbound.workflow.explainer')}</p>
      </Panel>
    </>
  );
}
