/**
 * FAQ content, copied from the official Ship My Cards FAQ.
 *
 *   Source:    https://www.shipmycards.com/faq/
 *   Retrieved: 2026-08-03
 *   Entries:   31 (the complete accordion, in source order)
 *
 * The question and answer text below is COPIED VERBATIM from the source page —
 * wording, conditions, exceptions and figures are reproduced as published and
 * must not be paraphrased, summarised or "corrected" in this file. The answers
 * were extracted from the page's own markup rather than a rendered summary, so
 * punctuation and emphasis survive intact.
 *
 * Three fields are Bault's, not the source's, and are the only editorial
 * additions:
 *
 *   `category`     The source page is a single flat accordion with no
 *                  categories and no stable anchors (its ids are generated by
 *                  its page builder). Categories and the `id` slugs here exist
 *                  so Bault can offer filtering and stable deep links.
 *   `availability` Whether Bault actually implements the workflow the answer
 *                  describes: `adapted` (Bault does this, with differences),
 *                  `partial` (the mechanism exists but part of what this entry
 *                  describes does not), or `unavailable` (no such capability).
 *
 *                  THIS FIELD ROTS IF IT IS NOT RE-CHECKED. It was first
 *                  captured on 2026-08-03 and left alone while the facilities,
 *                  inbound parcels, customs paperwork, group shipments,
 *                  shipment editing, insurance, tracker add-on, video review,
 *                  condition inspection and self-service top-up were all built.
 *                  By 2026-08-31 seventeen entries marked `unavailable`
 *                  described things Bault had been doing for weeks — the page
 *                  was telling paying customers that Bault could not do things
 *                  it does. Re-audit these two fields against the API whenever a
 *                  capability ships; the quoted text above them never changes.
 *   `baultNote`    What differs, or why the entry does not apply. Factual
 *                  statements about Bault's implementation — never a rewrite of
 *                  the source's policy language.
 *
 * No entry is presented as Bault policy. Nothing here is invented: an entry is
 * either copied and marked, or it is not present.
 *
 * Inline markers inside `text`: `**bold**` and `[[label|url]]` for links.
 * See `renderInline` in FaqLegalPage.tsx.
 *
 * GENERATED — regenerate rather than hand-editing prose, so the copy stays
 * faithful to the source.
 */

export type FaqAvailability = 'adapted' | 'partial' | 'unavailable';

export interface FaqInlineListItem {
  text: string;
  items?: string[];
}

export type FaqBlock =
  | { kind: 'p'; text: string }
  | { kind: 'h'; level: number; text: string }
  | { kind: 'ul'; items: FaqInlineListItem[] };

export interface FaqEntry {
  /** Stable slug used by deep links (`#/faq/faq?q=<id>`). */
  id: string;
  /** 0-based position in the source accordion, for the DIVE1 source mapping. */
  sourceIndex: number;
  question: string;
  category: string;
  availability: FaqAvailability;
  baultNote: string;
  blocks: FaqBlock[];
}

export interface FaqDocument {
  source: { url: string; retrieved: string; entryCount: number };
  categoryOrder: string[];
  entries: FaqEntry[];
}

export const FAQ: FaqDocument = {
  "source": {
    "url": "https://www.shipmycards.com/faq/",
    "retrieved": "2026-08-03",
    "entryCount": 31
  },
  "categoryOrder": [
    "getting-started",
    "intake",
    "addresses",
    "fees",
    "shipping",
    "services"
  ],
  "entries": [
    {
      "id": "how-does-shipmycards-work",
      "sourceIndex": 0,
      "question": "How does ShipMyCards work?",
      "category": "getting-started",
      "availability": "adapted",
      "baultNote": "Bault works the same way: you are issued a receiving address, you tell Bault a parcel is coming, and it moves expected → received → opened → contents booked into your vault → processed. The addresses are Bault's own facilities, not ShipMyCards'.",
      "blocks": [
        {
          "kind": "p",
          "text": "ShipMyCards acts as your hands and feet in the hobby by giving you a secure U.S. address and a personal online inventory for your cards—so you can buy in the U.S., consolidate packages, store safely, and ship when you’re ready."
        },
        {
          "kind": "h",
          "level": 4,
          "text": "[[**Here’s how it works**|https://www.shipmycards.com/getting-started/]]"
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**1) Buy cards anywhere in the U.S.**"
        },
        {
          "kind": "p",
          "text": "When you purchase cards from **eBay, Whatnot, card shops, breakers, or retailers**, ship them to [[**your ShipMyCards U.S. address**|https://www.shipmycards.com/services/shipping-addresses-instructions/]] instead of directly to your home."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**2) We receive and upload your cards**"
        },
        {
          "kind": "p",
          "text": "When your package arrives, we carefully receive it and **upload photos of each card** to your **online inventory**—usually **within 1 business day** of arrival at our **Arizona facility**."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**3) You decide what happens next**"
        },
        {
          "kind": "p",
          "text": "From your account, you can:"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Combine multiple purchases into one shipment** to save on postage"
            },
            {
              "text": "**Send cards for grading**"
            },
            {
              "text": "**Store cards securely** in our vault until you’re ready to ship"
            },
            {
              "text": "**Sell or trade cards** directly from your inventory"
            }
          ]
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**4) Ship and save**"
        },
        {
          "kind": "p",
          "text": "We pass our **shipping discounts** on to collectors, so you keep more money in your pocket to spend on **cards and other memorabilia**."
        },
        {
          "kind": "p",
          "text": "**Optional insurance: **We partner with a **third-party insurance provider**, allowing you to **insure shipments (up to $5,000)** while still declaring a **lower customs value**—helping you manage risk without unnecessary fees."
        }
      ]
    },
    {
      "id": "how-is-shipmycards-different-than-other-shipping-services",
      "sourceIndex": 1,
      "question": "How is ShipMyCards different than other shipping Services?",
      "category": "getting-started",
      "availability": "adapted",
      "baultNote": "All three differentiators exist here. Two receiving addresses, one of them in a state that levies no sales tax; White Glove hand delivery, quoted per journey; and a middleman for private deals — Bault's escrow, where the money is genuinely held as a ledger entry and released against an inspection window agreed before either side commits.",
      "blocks": [
        {
          "kind": "p",
          "text": "ShipMyCards is more than a shipping address—we are a collector-focused service that helps you buy in the U.S., manage your inventory online, and decide exactly what happens next: [[**store, consolidate, ship, grade, sell, or request additional services**.|https://www.shipmycards.com/services/]]"
        },
        {
          "kind": "p",
          "text": "Many online sellers will not ship outside the United States—ShipMyCards is the solution. If you live outside the U.S., you can use ShipMyCards as your [[**U.S. shipping address**|https://www.shipmycards.com/services/shipping-addresses-instructions/]] when shopping online."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**What makes ShipMyCards different**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Collector-built, family-owned service:** Collector-owned, family business with real support and direct communication—personal service designed around how collectors actually buy, store, and ship"
            },
            {
              "text": "**ShipMyCards is a registered and insured business, built by collectors for collectors.**"
            },
            {
              "text": "**Two U.S. address options**, including an **Oregon address** for eligible tax-free eBay purchases"
            },
            {
              "text": "[[**Online inventory with photos**|https://www.shipmycards.com/services/shipping-addresses-instructions/]] so you can manage your cards and collectibles from anywhere"
            },
            {
              "text": "**Everyday processing** of incoming items for consistent intake and uploads"
            },
            {
              "text": "**Discounted shipping rates** are passed on to collectors"
            },
            {
              "text": "**Optional insurance up to $5,000** through a third-party provider"
            },
            {
              "text": "**Collector services beyond shipping**, including:",
              "items": [
                "[[**White Glove service**|https://www.shipmycards.com/services/white-glove-delivery/]] for high-touch handling and special requests",
                "[[**Middleman service**|https://www.shipmycards.com/services/middleman-escrow/]], a trusted third-party receiving/verification support for deals and transactions",
                "[[**PSA Grading Submissions **|https://www.shipmycards.com/services/psa-grading/]]",
                "Partnerships with **[[consignment|https://www.shipmycards.com/services/consignment-options-private-sales/]] companies**"
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "why-shipmycards-is-great-for-u-s-based-collectors",
      "sourceIndex": 2,
      "question": "Why ShipMyCards is great for U.S.-based collectors?",
      "category": "getting-started",
      "availability": "adapted",
      "baultNote": "Same idea, different state: Bault's tax-free forwarding facility is in Delaware rather than Oregon. Bault records each facility's destination sales-tax rate and shows what a purchase would cost at each address — as guidance only. Bault is not the seller and neither collects nor remits anybody's sales tax.",
      "blocks": [
        {
          "kind": "p",
          "text": "ShipMyCards is designed to help U.S. collectors **save money on purchases**, keep their collection organized, and move quickly when it’s time to [[**ship, grade, sell, or trade**|https://www.shipmycards.com/services/]]."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Key benefits for U.S. collectors**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Big savings with our Oregon address (tax advantage) ** Use the **ShipMyCards Oregon address** for eligible eBay purchases to help **eliminate sales tax**, which can add up fast—especially on higher-value cards and sealed product."
            },
            {
              "text": "[[**A true vault service with faster turnaround **|https://www.shipmycards.com/services/collector-mailbox-and-vault-services/]] Your items are not just stored—they are accessible. ShipMyCards is a **vault-style service** with **quicker turnaround times** when you are ready to take action, whether that’s shipping, grading, or selling. Many vault services are slower to process requests—ours is built for hobby speed."
            },
            {
              "text": "**Online inventory + photos (know exactly what you have) ** Keep everything organized in one place with a **photo-based online inventory**, so you can track purchases, plan submissions, and manage your collection without digging through boxes."
            },
            {
              "text": "**Consolidation + discounted shipping rates ** Combine purchases from multiple sellers and take advantage of **discounted shipping rates** when you’re ready to send items out."
            },
            {
              "text": "**Premium collector services when you need extra support ** Request [[**White Glove**|https://www.shipmycards.com/services/white-glove-delivery/]] handling for special items, use [[**Middleman**|https://www.shipmycards.com/services/middleman-escrow/]] service for deals, or submit cards for [[**grading**|https://www.shipmycards.com/services/psa-grading/]]—all while your items stay safely in your inventory."
            },
            {
              "text": "**Real support from a collector-owned, family-run team ** Collector-owned, family business with direct communication and personal service—built around how collectors actually buy, store, and ship."
            }
          ]
        }
      ]
    },
    {
      "id": "why-shipmycards-is-great-for-international-collectors",
      "sourceIndex": 3,
      "question": "Why ShipMyCards is great for international collectors?",
      "category": "getting-started",
      "availability": "adapted",
      "baultNote": "Bault issues each account a U.S. address in the form 'Bault C/O <username>', which is what an overseas buyer gives a U.S. seller. An arrival shipped from outside the country is flagged, and the duty obligation is recorded on the parcel rather than left in a policy document.",
      "blocks": [
        {
          "kind": "p",
          "text": "ShipMyCards makes it easier to buy from U.S. sellers, manage your collection remotely, and control when (and how) you ship everything home."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Key benefits for international collectors**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "[[**Your U.S. shipping address **|https://www.shipmycards.com/services/collector-mailbox-and-vault-services/]] Many U.S. sellers will not ship internationally—ShipMyCards gives you a reliable **U.S. address** so you can still buy the items you want."
            },
            {
              "text": "**Oregon address savings (tax advantage) ** Use the **ShipMyCards Oregon address** for eligible eBay purchases to help **reduce or eliminate sales tax**, which can make a big difference on higher-value cards and sealed product."
            },
            {
              "text": "**Consolidation to reduce international postage ** Combine multiple U.S. purchases into **fewer shipments** to help lower overall international shipping costs compared to mailing packages one by one from different sellers."
            },
            {
              "text": "**Online inventory + photos (manage remotely) ** Your items are uploaded into a **photo-based online inventory**, so you can review what arrived, plan shipments, and make decisions from anywhere in the world."
            },
            {
              "text": "**Shipping options with tracking + optional insurance ** Choose shipping options with tracking and add **optional insurance up to $5,000** through a third-party provider."
            },
            {
              "text": "**Extra support when it matters most ** Use [[**White Glove**|https://www.shipmycards.com/services/white-glove-delivery/]] for special handling and [[**Middleman**|https://www.shipmycards.com/services/middleman-escrow/]] service for important deals or transactions that need trusted third-party support."
            }
          ]
        }
      ]
    },
    {
      "id": "shipping-to-australia-customs-clearance-guide",
      "sourceIndex": 4,
      "question": "Shipping to Australia: Customs Clearance Guide",
      "category": "shipping",
      "availability": "partial",
      "baultNote": "Bault generates a full commercial invoice for every international parcel — one line per item with description, declared value, HS code, country of origin and weight — and publishes destination guidance with a link to the destination's own customs authority. It does NOT lodge a FedEx assembly order or any other broker-side clearance instruction, which is what this entry is largely about.",
      "blocks": [
        {
          "kind": "h",
          "level": 4,
          "text": "**Australia Customs Clearance FAQ**"
        },
        {
          "kind": "p",
          "text": "Australian customs may review any international shipment, regardless of its weight or value."
        },
        {
          "kind": "p",
          "text": "ShipMyCards packages may be classified as Assembly Orders because they can contain items purchased from multiple sellers and combined into one shipment. **FedEx may not always provide customs brokerage for Assembly Orders.**"
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**When might I need a customs broker?**"
        },
        {
          "kind": "p",
          "text": "You will need to hire an independent licensed customs broker if your Assembly Order requires formal or additional customs clearance, including when:"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "The customs value exceeds $1,000AUD (Including Postage) – **This amount will always need a Customs Broker and Formal Entry Regardless of the Carrier. FedEx and other Carriers can broker this for you only if it is from a single Seller, otherwise you will need an independent Broker.**"
            },
            {
              "text": "FedEx or Australian customs requests additional clearance"
            },
            {
              "text": "The shipment is selected for an audit or further review"
            }
          ]
        },
        {
          "kind": "p",
          "text": "Based on collector’s recent experiences, packages weighing more than 10 pounds may be more likely to receive additional review. However, this is not an official customs threshold, and packages of any weight or value may be reviewed."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Who is responsible for customs clearance?**"
        },
        {
          "kind": "p",
          "text": "The recipient in Australia is responsible for:"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "Responding to FedEx or Australian customs"
            },
            {
              "text": "Providing requested documents"
            },
            {
              "text": "Hiring a customs broker when required"
            },
            {
              "text": "Paying applicable duties, taxes, brokerage fees, and government charges"
            }
          ]
        },
        {
          "kind": "p",
          "text": "ShipMyCards will provide the shipment information available to us. However, because ShipMyCards did not purchase the items, we may not have the recipient’s original purchase receipts or payment records."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Can ShipMyCards change the declared value or description?**"
        },
        {
          "kind": "p",
          "text": "No. ShipMyCards must provide accurate shipment information."
        },
        {
          "kind": "p",
          "text": "Collectors should not request that ShipMyCards:"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "Lower the declared value"
            },
            {
              "text": "Provide an inaccurate description"
            },
            {
              "text": "Divide a shipment for the purpose of avoiding taxes or customs requirements"
            },
            {
              "text": "Submit information that does not accurately reflect the shipment"
            }
          ]
        },
        {
          "kind": "p",
          "text": "Providing inaccurate customs information may cause delays, additional charges, seizure, penalties, or other consequences**.**"
        },
        {
          "kind": "p",
          "text": "**Important**"
        },
        {
          "kind": "p",
          "text": "A package under $1,000AUD or under 10 pounds may still be reviewed and require an independent customs broker. Customs requirements are determined by Australian authories. FedEx will transport the shipment but will not act as the customs broker for an assembly order."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**What happens if a broker is required?**"
        },
        {
          "kind": "p",
          "text": "If FedEx or Australian authorities advise that an independent customs broker is required, the recipient must locate and appoint a licensed Australian customs broker."
        },
        {
          "kind": "p",
          "text": "The recipient should follow the instructions provided by FedEx and the broker. ShipMyCards can provide available shipment documents but cannot act as the importer or customs broker."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Finding an Australian Customs Broker**"
        },
        {
          "kind": "p",
          "text": "The following customs brokers have previously been used by ShipMyCards collectors:"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Platinum Freight Management **[[https://platinumfreight.com.au/|https://platinumfreight.com.au/]]"
            },
            {
              "text": "**Australian Customs Clearance **[[https://aucustomsclearance.com.au/|https://aucustomsclearance.com.au/]]"
            },
            {
              "text": "**JWI Customs **[[https://jwicustoms.com.au/|https://jwicustoms.com.au/]]"
            },
            {
              "text": "**Complete List of Australia Customs Brokers **[[https://www.abf.gov.au/licensing/brokers/brokerages|https://www.abf.gov.au/licensing/brokers/brokerages]]"
            }
          ]
        },
        {
          "kind": "p",
          "text": "ShipMyCards is not affiliated with these companies and does not recommend or endorse one broker over another. This list is provided only as a helpful starting point because other ShipMyCards collectors have reported using these brokers."
        },
        {
          "kind": "p",
          "text": "Collectors are responsible for researching, selecting, and hiring their own customs broker. Services, pricing, availability, and acceptance of a specific shipment must be confirmed directly with the broker. ShipMyCards cannot guarantee that a listed broker will accept or successfully clear a shipment."
        },
        {
          "kind": "p",
          "text": "Collectors may also locate another licensed Australian customs broker independently."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**What happens if the recipient does not complete customs clearance?**"
        },
        {
          "kind": "p",
          "text": "The shipment may be delayed, held, returned, abandoned, or otherwise handled according to carrier and government procedures."
        },
        {
          "kind": "p",
          "text": "The recipient will be responsible for any additional charges, including:"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "Storage fees"
            },
            {
              "text": "Brokerage fees"
            },
            {
              "text": "Government fees"
            },
            {
              "text": "Return transportation"
            },
            {
              "text": "Duties or taxes"
            },
            {
              "text": "Other carrier-related charges"
            }
          ]
        },
        {
          "kind": "p",
          "text": "This information is general guidance and is not legal, tax, or customs-brokerage advice."
        }
      ]
    },
    {
      "id": "what-are-the-fees-for-using-shipmycards",
      "sourceIndex": 5,
      "question": "What are the fees for using ShipMyCards?",
      "category": "fees",
      "availability": "adapted",
      "baultNote": "Bault charges per-action fees and automatic storage fees, and publishes a price list you can read before being charged. Every amount comes from Bault's own effective-dated pricing rules, not from the figures quoted here, and each charge stores a snapshot of the rule that produced it.",
      "blocks": [
        {
          "kind": "p",
          "text": "ShipMyCards uses a simple **pay-for-what-you-send** model: **no memberships** and **no monthly fees**. You are charged when **packages arrive** (incoming processing) and when you choose to **ship or take action** (shipping, grading submissions, etc.)."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**What your total cost depends on:**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Which address you use**: [[Arizona or Oregon|https://www.shipmycards.com/services/shipping-addresses-instructions/]]"
            },
            {
              "text": "**What you send**: cards, slabs, boxes, sealed wax, comics, misc items"
            },
            {
              "text": "**What you do next**: store, consolidate, grade, sell, or ship"
            }
          ]
        },
        {
          "kind": "p",
          "text": "Here is a simple breakdown of the fees we charge for incoming packages:"
        },
        {
          "kind": "h",
          "level": 5,
          "text": "[[**Arizona Price List**|https://www.shipmycards.com/services/service-fees/]]"
        },
        {
          "kind": "p",
          "text": "$2 Package Processing fee + the following fees:"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Cards**",
              "items": [
                "$1 per individual card (5 or less cards always done as Individuals)",
                "$5 Card Lot –Up to a Graded Card Box (20 slabs or 100 Top loaders, $5 per extra Box)",
                "$5 Oversized Card (Oversized Slabs, etc.)"
              ]
            },
            {
              "text": "**Boxes of Cards**",
              "items": [
                "$5 Pack of cards",
                "$5 Per each Regular Sized Box of Cards ($20 for up to 12 Boxes)",
                "$20 Sealed Case",
                "$5 Pokémon ETB or Small Collection Box.",
                "$10 Per large Pokémon Collection Box or Ultra-Premium Collection"
              ]
            },
            {
              "text": "**Comics/ Magazines**",
              "items": [
                "$5 Comic Book Raw (Top Loader provided if needed)",
                "$10 Comic Book Lot (Raw Comics 2-10 Comics)",
                "$5 Per Graded Comic Book",
                "$5 Per Magazine (top Loader provided if needed)"
              ]
            },
            {
              "text": "**Misc items**",
              "items": [
                "$5 Jersey each (bagged or boxed)",
                "$5 Shirts or Shorts (small misc. Clothing)",
                "$10 Jacket / Pants",
                "$20 Pair of Shoes",
                "$20 Basketball/Football/Helmet/Skateboard",
                "$3 Hot Wheel car",
                "$8 Hot Wheel Lot (up to 5 cars, $1 per after)",
                "$5 Any Misc Small Item (up to 4”x4” in. – Watch, Funko Pop, Figurine, Coins)",
                "$8 Vinyl Record (each)"
              ]
            }
          ]
        },
        {
          "kind": "p",
          "text": "No Maximum fees for Oversized Items or Large Lots. Please verify fees before sending Large Items or Large lots."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "[[**Oregon Price List**|https://www.shipmycards.com/services/service-fees/]]"
        },
        {
          "kind": "p",
          "text": "$5 Package Processing fee + the following fees:"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Cards**",
              "items": [
                "$2 per individual card (5 or less cards always done as Individuals)",
                "$10 Card Lot –Up to a Graded Card Box (20 slabs or 100 Top loaders, $10 per Box)",
                "$10 Oversized Card (Oversized Slabs, etc.)"
              ]
            },
            {
              "text": "**Boxes of Cards**",
              "items": [
                "$10 Pack of cards (up to 10 packs)",
                "$10 Per each Regular Sized Box of Cards ($30 for up to 4 Boxes)",
                "$45 Sealed Case",
                "$10 Per Pokémon ETB or Small Collection Box.",
                "$15 Per large Pokémon Collection Box or Ultra-Premium Collection"
              ]
            },
            {
              "text": "**Comics/ Magazines**",
              "items": [
                "$10 Comic Book Raw (Top Loader provided if needed)",
                "$15 Comic Book Lot (Raw Comics 2-10 Comics)",
                "$15 Per Graded Comic Book",
                "$15 Per Magazine (top Loader provided if needed)"
              ]
            },
            {
              "text": "**Misc items**",
              "items": [
                "$10 Jersey each (bagged or boxed)",
                "$10 Shirts or Shorts (small misc. Clothing)",
                "$20 Jacket / Pants",
                "$30 Pair of Shoes",
                "$45 Basketball/Football/Helmet/Skateboard",
                "$5 Hot Wheels",
                "$15 Hot Wheel Lot (up to 5 cars, $3 per after)",
                "$15 Any Misc Small Item (up to 4”x4” in. – watch, Funko Pop, figurine, coins)",
                "$15 Vinyl Record (each)"
              ]
            },
            {
              "text": "No Oversized Items or Large Lots allowed without Prior Approval. Please verify fees before sending Large Items or Large lots as many times the additional Shipment Cost does not offset the tax savings."
            }
          ]
        },
        {
          "kind": "p",
          "text": "Any freebie / dummy cards will be given away if not worth the processing charge."
        },
        {
          "kind": "p",
          "text": "Since you do not buy the cards from us, we do not know what you paid for the cards. It is required that you place the outgoing customs value on the package through the shipment request if it is required for your country."
        },
        {
          "kind": "h",
          "level": 3,
          "text": "Storage Fees"
        },
        {
          "kind": "p",
          "text": "We offer storage for up to 180 days with the initial costs. Thereafter, we offer additional storage for a cost of 10% each additional 90 days."
        },
        {
          "kind": "p",
          "text": "Example: Item #9999 was added to the inventory on 06/01/2025 with the initial cost of $1. If item is not shipped before or on 11/28/2025 (pass 180 days), additional storage fee of $0.10 (10% of initial cost) will be directly debited from the store credit for each additional 90 days."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "LARGE ITEM EXPECTATIONS(90-DAY POLICY)"
        },
        {
          "kind": "p",
          "text": "Large items must be shipped home within **90 days**."
        },
        {
          "kind": "p",
          "text": "Large Items remaining in storage after 90 days will be **recharged the original incoming processing fee** due to limited warehouse space. Large items cannot be held long-term. The original incoming processing fee will be recharged each additional 90 days."
        }
      ]
    },
    {
      "id": "do-you-accept-any-non-card-items",
      "sourceIndex": 6,
      "question": "Do you accept any non-Card items?",
      "category": "intake",
      "availability": "adapted",
      "baultNote": "Bault publishes its own accepted-and-refused list under FAQ & Legal > What we accept: twelve accepted item classes with their storage terms and lot rules, and the categories refused outright with the reason for each. That page is generated from the same modules intake validates against, so it cannot drift from what is actually enforced. The specific policy quoted here is ShipMyCards'.",
      "blocks": [
        {
          "kind": "p",
          "text": "Yes. While ShipMyCards specializes in trading cards, we also accept many **collector-related items and memorabilia**."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Common non-card items we accept**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Comic books** (raw and graded)"
            },
            {
              "text": "**Sealed packs, boxes, and cases** of cards"
            },
            {
              "text": "**Pokémon ETBs** and collection boxes"
            },
            {
              "text": "**Sports memorabilia** (jerseys, balls, helmets, etc.)"
            },
            {
              "text": "**Other small collectible items**"
            }
          ]
        },
        {
          "kind": "p",
          "text": "If an item is collector-related, it’s usually fine. If you’re unsure, please **check with an admin before shipping** to avoid delays."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Items we do NOT accept**"
        },
        {
          "kind": "p",
          "text": "For safety, legal, and security reasons, we cannot accept:"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "Glass, liquids, oils, or gases"
            },
            {
              "text": "Flammable items"
            },
            {
              "text": "Drugs, medicine, or supplements"
            },
            {
              "text": "Makeup or perfume"
            },
            {
              "text": "Items containing lithium batteries"
            },
            {
              "text": "GPS trackers (including Apple AirTags)"
            },
            {
              "text": "Pornographic cards or magazines (including Playboy)"
            }
          ]
        },
        {
          "kind": "p",
          "text": "**Restricted items may be discarded without return.**"
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Important note on GPS trackers (Apple AirTags, etc.)**"
        },
        {
          "kind": "p",
          "text": "To protect collector security, we keep our warehouse location private. If a GPS tracker is found in a shipment:"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "It will be taken to our sister location, Westgate Cards and Collectibles"
            },
            {
              "text": "The battery will be removed"
            },
            {
              "text": "The tracker will be disposed of"
            }
          ]
        },
        {
          "kind": "p",
          "text": "This policy helps protect both collectors and our facility."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Large items and storage expectations (90-day policy)**"
        },
        {
          "kind": "p",
          "text": "Because warehouse space is limited, **large items must be shipped home within 90 days** of arrival."
        },
        {
          "kind": "p",
          "text": "If a large item stays in storage **longer than 90 days**, the **original incoming processing fee will be charged again. **This helps cover additional handling/storage and keeps intake times fast for all collectors."
        }
      ]
    },
    {
      "id": "do-we-allow-gps-trackers-for-incoming-shipments",
      "sourceIndex": 7,
      "question": "Do we allow GPS Trackers for incoming shipments?",
      "category": "intake",
      "availability": "adapted",
      "baultNote": "Same rule, and Bault now states it in advance on its own intake policy page: do not put a tracker in a parcel you send. One found in an arriving parcel is removed, destroyed, recorded as an arrival disposal and notified to you. Bault does sell a tracker as an outbound add-on, which is not a contradiction: that one travels in a parcel Bault packed, declared and insured, and is handed to you on delivery.",
      "blocks": [
        {
          "kind": "p",
          "text": "No. Due to the confidentiality and security protocols of our vault, we do not allow GPS trackers such as Apple AirTags or similar devices. If a tracking device arrives with your shipment, it will be taken to our sister location, Westgate Cards, the battery will be removed and air tag disposed of."
        }
      ]
    },
    {
      "id": "what-address-should-i-use-for-my-account",
      "sourceIndex": 8,
      "question": "What address should I use for my account?",
      "category": "addresses",
      "availability": "adapted",
      "baultNote": "Bault gives each account its receiving addresses under Inbound, addressed as 'Bault C/O <username>'. The C/O line is generated from your own account, so it cannot name somebody else. The addresses listed in this answer are ShipMyCards'.",
      "blocks": [
        {
          "kind": "h",
          "level": 5,
          "text": "**Arizona Address (default for most items)**"
        },
        {
          "kind": "p",
          "text": "Use this address for **all non-eBay purchases** (Facebook, Instagram, Blowout, breakers, etc.)."
        },
        {
          "kind": "p",
          "text": "**ShipMyCards ** C/O Your Username 591 E Plaza Cir, Unit 2294 Litchfield Park, AZ 85340"
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Oregon Address (tax-free eBay purchases $45+)**"
        },
        {
          "kind": "p",
          "text": "Use this address for **card purchases of $45 or more on eBay** to eliminate sales tax."
        },
        {
          "kind": "p",
          "text": "**ShipMyCards ** C/O Your Username 491 3rd St, Unit 339 Lafayette, OR 97127"
        },
        {
          "kind": "p",
          "text": "**Phone number (use for both addresses):** 623-889-4589"
        },
        {
          "kind": "p",
          "text": "**Reminder:** Always request tracking and make sure your **username and unit number** are included on the label."
        }
      ]
    },
    {
      "id": "what-is-the-benefit-of-mailing-to-oregon",
      "sourceIndex": 9,
      "question": "What is the benefit of mailing to Oregon?",
      "category": "addresses",
      "availability": "adapted",
      "baultNote": "The same benefit, from Delaware rather than Oregon: it levies no sales tax, so a purchase shipped there is not charged any. Bault shows the estimated destination tax at each of its addresses before you buy. Guidance only — Bault is not the seller.",
      "blocks": [
        {
          "kind": "p",
          "text": "The main benefit of using the ShipMyCards **Oregon address** is **sales tax savings**. Oregon has **no sales tax**, while Arizona’s sales tax is **8.8%**. For many eBay purchases, the tax savings can offset the [[**$4 forwarding fee**|https://www.shipmycards.com/services/service-fees/]] (break-even is roughly a **$45** card purchase)."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**When should I use the Oregon address?**"
        },
        {
          "kind": "p",
          "text": "Use the Oregon address for **eBay card purchases around $45+** (single cards or lots). This is most helpful on platforms that are required to collect state sales tax, such as **eBay**."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**When should I use the Arizona address instead?**"
        },
        {
          "kind": "p",
          "text": "Use the Arizona address for:"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**All non-eBay purchases** (Facebook, Instagram, box breaks, Blowout, retailers, etc.)"
            },
            {
              "text": "**Lower-priced eBay items** (generally under $45)"
            }
          ]
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**How Oregon forwarding works**"
        },
        {
          "kind": "p",
          "text": "All items sent to Oregon are forwarded to our Arizona facility via **FedEx**."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Quick examples of sales tax savings (8.8%)**"
        },
        {
          "kind": "p",
          "text": "Here’s what the sales tax would be on an Arizona-taxed purchase (and what you may avoid by using Oregon for eligible eBay purchases):"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**$100 card: $8.80** sales tax"
            },
            {
              "text": "**$500 card: $44.00** sales tax"
            },
            {
              "text": "**$1,000 card: $88.00** sales tax"
            }
          ]
        },
        {
          "kind": "p",
          "text": "(Reminder: Oregon forwarding includes a $4 forwarding fee, so the net savings depends on the purchase amount and the item/package details.)"
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Tip: Save both addresses in eBay**"
        },
        {
          "kind": "p",
          "text": "If you buy both low-end and high-end cards on eBay, save **both [[ShipMyCards addresses|https://www.shipmycards.com/services/shipping-addresses-instructions/]]** in eBay so you can pick the best option at checkout."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Note on larger/heavier packages**"
        },
        {
          "kind": "p",
          "text": "Larger or heavier items have higher forwarding costs. However, the tax savings may still be worth it, please **create an helpdesk ticket on the website **so we can help estimate potential savings."
        }
      ]
    },
    {
      "id": "how-do-i-purchase-store-credit",
      "sourceIndex": 10,
      "question": "How do I purchase Store Credit?",
      "category": "fees",
      "availability": "adapted",
      "baultNote": "Bault funds a wallet two ways: a card payment, which settles immediately, or a bank transfer, which raises a cash-in request that staff reconcile against the arriving payment. PayPal Friends & Family and Wise are ShipMyCards' rails, not Bault's.",
      "blocks": [
        {
          "kind": "p",
          "text": "You can purchase ShipMyCards Store Credit using **PayPal** (Goods & Services or Friends & Family) or a **bank transfer** (Wise/Revolut). Choose the option that works best for your location and transfer amount."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "Option 1: PayPal (Goods & Services)"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Use the ShipMyCards website checkout** for all **PayPal Goods & Services** payments."
            },
            {
              "text": "Please **do not** send Goods & Services as a direct PayPal payment."
            }
          ]
        },
        {
          "kind": "p",
          "text": "Why: It keeps payments matched correctly and processed automatically."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "Option 2: PayPal (Friends & Family)"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "You may send **PayPal Friends & Family** directly to: **shipmycards@gmail.com**"
            },
            {
              "text": "These are **updated manually** (we pull reports multiple times per day and apply credit)"
            }
          ]
        },
        {
          "kind": "p",
          "text": "**Tip:** PayPal often still applies fees, but **Friends & Family is usually best for international collectors when the payment is over $100**."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "Option 3: Bank Transfer (Wise / Revolut)"
        },
        {
          "kind": "p",
          "text": "We also accept bank transfers—many collectors use **Wise** or **Revolut** because they often provide **better exchange rates** than PayPal."
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "To send via Wise, you can send to: **ShipMyCards@gmail.com**"
            },
            {
              "text": "Wise invite link (may waive transfer fees up to $600 in transfers): [[https://wise.com/invite/u/bryanw332|https://wise.com/invite/u/bryanw332]]"
            }
          ]
        }
      ]
    },
    {
      "id": "what-shipping-options-do-you-offer",
      "sourceIndex": 11,
      "question": "What shipping options do you offer?",
      "category": "shipping",
      "availability": "adapted",
      "baultNote": "Bault does return carrier and service-level options for a shipment, each with its own insurance ceiling and whether a signature can be demanded. They come from Bault's own carrier catalogue; the USPS/FedEx/ePost/ePacket line-up and the prices quoted here are ShipMyCards'.",
      "blocks": [
        {
          "kind": "p",
          "text": "ShipMyCards partners with **USPS and FedEx** through **contracted, discounted shipping rates**. These negotiated rates allow us to offer **reliable service and significant shipping savings**, which we pass directly on to our collectors."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Domestic (U.S.) shipping**"
        },
        {
          "kind": "p",
          "text": "Both **USPS and FedEx are excellent options for domestic (U.S.) shipments**, and the best choice often depends on the receiver’s address, value of package, and package size."
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**USPS First Class** is typically the cheapest option for packages **under 1 lb**"
            },
            {
              "text": "**USPS Priority and FedEx Padded Packs** are commonly in the **$10–$15 range** (postage is based on weight and dimensions)."
            }
          ]
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**International shipping**"
        },
        {
          "kind": "p",
          "text": "International options include **FedEx, ePost, and ePacket**. Availability depends on destination country, package size, and declared value. All shipments include **tracking** and our contracted rates help reduce postage."
        },
        {
          "kind": "h",
          "level": 6,
          "text": "**FedEx Benefits**"
        },
        {
          "kind": "p",
          "text": "FedEx is our most-used international option because it’s usually the best all-around choice for **price, speed, and tracking**—and we have strong support if anything comes up."
        },
        {
          "kind": "p",
          "text": "**Why collectors choose FedEx**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "Often **less expensive than ePost** on many shipments"
            },
            {
              "text": "Typically **faster** with **more detailed tracking** than other options"
            },
            {
              "text": "We have a **dedicated FedEx support team** to help resolve issues quickly if a shipment needs attention"
            },
            {
              "text": "FedEx rates are based on **dimensional weight** (until actual weight exceeds dimensional weight) To calculate the dimensional weight of your box use formula **(L × W × H) / 167**"
            },
            {
              "text": "We use **custom-sized boxes** to help keep dimensional weight (and cost) efficient"
            }
          ]
        },
        {
          "kind": "h",
          "level": 6,
          "text": "**ePost benefits and restrictions**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "Postage amount is charged **per pound**."
            },
            {
              "text": "Weight limit of **20 lbs** (if over 20 lbs will be **split into 2 separate shipments)**"
            },
            {
              "text": "Max package size: **45″ diagonal**"
            },
            {
              "text": "Max insurance: **$2,000** (purchased separately)"
            }
          ]
        },
        {
          "kind": "p",
          "text": "**ePost EMS (by request):** Not in the dropdown menu—request it in shipment comments. Typically **5–10 day service level** and can be insured up to **$5,000**."
        },
        {
          "kind": "h",
          "level": 6,
          "text": "**ePacket benefits and restrictions**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "Lowest cost for small packages to **32 contracted countries**"
            },
            {
              "text": "Postage amount is charged **per ounce**"
            },
            {
              "text": "Max weight: **4 lbs (64 oz)**"
            },
            {
              "text": "Max customs value: **$400**"
            },
            {
              "text": "Max insurance: **$500**"
            },
            {
              "text": "Max dimensions: **Length 24″** and **L+W+H 36″**"
            },
            {
              "text": "Tracking:[[ **https://epgtrack.com**|https://epgtrack.com]]"
            }
          ]
        },
        {
          "kind": "p",
          "text": "**ePacket countries include:** Australia, Belgium, Canada, Croatia, Denmark, Estonia, Finland, France, Germany, Gibraltar, Greece, Hong Kong, Iceland, India, Ireland, Israel, Italy, Japan, Lithuania, Luxembourg, Malaysia, Netherlands, New Zealand, Poland, Portugal, Singapore, South Korea, Sweden, Switzerland, Thailand, United Kingdom."
        }
      ]
    },
    {
      "id": "what-s-the-difference-between-simple-shipping-and-personalized-shippin",
      "sourceIndex": 12,
      "question": "What’s the difference between Simple Shipping and Personalized Shipping?",
      "category": "shipping",
      "availability": "adapted",
      "baultNote": "Bault has both modes. A shipment request carries a service mode of 'simple' or 'personalised', and the difference is the same one described here: how much say you have over carrier and packing versus letting Bault choose the cheapest sensible option.",
      "blocks": [
        {
          "kind": "h",
          "level": 5,
          "text": "**Simple Shipping (we choose for you)**"
        },
        {
          "kind": "p",
          "text": "Best for collectors who want the **easiest and fastest option**."
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "ShipMyCards selects the **best carrier and service** for your shipment"
            },
            {
              "text": "Optimized for **value, speed, and safety**"
            },
            {
              "text": "You only choose:",
              "items": [
                "Standard or Rush processing",
                "Signature requirement",
                "Optional insurance",
                "Customs value (if required)"
              ]
            }
          ]
        },
        {
          "kind": "p",
          "text": "[[How to Make a Shipment Request in less than 1 Minute|https://youtu.be/3LC84U8gsIc?si=UvqtRd-CCOCfitOP]]"
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Personalized Shipping (you choose)**"
        },
        {
          "kind": "p",
          "text": "Best for collectors who want **full control**."
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "Choose your **carrier and service**:",
              "items": [
                "**FedEx** – fastest and most reliable international option",
                "**ePost (USPS)** – USPS International Priority option",
                "**ePacket (USPS)** – cheapest postage for small, low-value shipments to select countries"
              ]
            },
            {
              "text": "Add notes or special handling requests"
            },
            {
              "text": "Option to see postage estimates"
            },
            {
              "text": "Enter customs values per item (if required)"
            }
          ]
        },
        {
          "kind": "p",
          "text": "Ideal for domestic and international shipments, high-value cards, or special requests"
        },
        {
          "kind": "p",
          "text": "[[How to Create a Personalized Shipment|https://youtu.be/41F9FAR5WZU?si=hvK1_lNz9EC3HjLk]]"
        }
      ]
    },
    {
      "id": "how-do-i-make-a-shipment-request",
      "sourceIndex": 13,
      "question": "How do I make a shipment request?",
      "category": "shipping",
      "availability": "partial",
      "baultNote": "Bault's own written walkthroughs are under FAQ & Legal > Guides, with the steps and the screen each one happens on. Bault has no video tutorials, and this entry's answer is a set of links to ShipMyCards' own.",
      "blocks": [
        {
          "kind": "p",
          "text": "Please watch our videos on our ShipMyCards **YouTube** page for a quick step-by-step tutorial."
        },
        {
          "kind": "p",
          "text": "[[**How to Make a Shipment Request in Less than 1 Minute**|https://youtu.be/3LC84U8gsIc?si=-BAM9JkwJ6hV7hq2]]"
        },
        {
          "kind": "p",
          "text": "[[**How to Create a Personalized Shipment **|https://youtu.be/41F9FAR5WZU?si=1XkMs-OXOapYA6r7]]"
        }
      ]
    },
    {
      "id": "can-i-add-remove-items-to-a-pending-shipment-request",
      "sourceIndex": 14,
      "question": "Can I add/remove Items to a Pending shipment request?",
      "category": "shipping",
      "availability": "adapted",
      "baultNote": "Bault lets you add items to, remove items from, or cancel a shipment while it still reads 'requested'. Once a rate is selected the parcel has been paid for and an operator may already be holding it, so the window closes there — which is the same cutoff described here.",
      "blocks": [
        {
          "kind": "p",
          "text": "Yes. ShipMyCards now allows you to **add or remove items** from a pending shipment request—as long as our team has **not already pulled your items** for packing."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "When can I edit a shipment?"
        },
        {
          "kind": "p",
          "text": "You can make changes while the shipment status shows **“Requested.”** This means our team **has not started pulling** and preparing your shipment yet."
        },
        {
          "kind": "p",
          "text": "Watch the video on our ShipMyCards **YouTube** page for a quick step-by-step tutorial."
        }
      ]
    },
    {
      "id": "is-there-a-way-to-get-a-postage-quote-prior-to-requesting-my-shipment",
      "sourceIndex": 15,
      "question": "Is there a way to get a postage quote prior to Requesting my Shipment?",
      "category": "shipping",
      "availability": "adapted",
      "baultNote": "Bault quotes postage before anything is created: a quote request prices a hypothetical parcel for the items and address you name, with no shipment raised. The dollar ranges quoted in this answer are ShipMyCards'.",
      "blocks": [
        {
          "kind": "p",
          "text": "Yes. Our shipment request now allows you to **view postage quotes** based on the **estimated size and weight** of your package."
        },
        {
          "kind": "p",
          "text": "Below are sample estimates for **2 lb** and **4 lb** packages using the most cost-effective options, since many shipments fall in this range."
        },
        {
          "kind": "h",
          "level": 6,
          "text": "**2-pound package (about 10 slabs or 50 toploaders)**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**FedEx:** usually **$40–$55**"
            },
            {
              "text": "**ePacket*: $22–$31**"
            },
            {
              "text": "**ePost Priority:** around **$55**"
            },
            {
              "text": "**ePost EMS:** around **$60**"
            }
          ]
        },
        {
          "kind": "h",
          "level": 6,
          "text": "**4-pound package (about 20 slabs or 100 toploaders)**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**FedEx:** usually **$50–$67**"
            },
            {
              "text": "**ePacket*: $40–$51**"
            },
            {
              "text": "**ePost Priority: $75**"
            },
            {
              "text": "**ePost EMS: $77**"
            }
          ]
        },
        {
          "kind": "h",
          "level": 6,
          "text": "**Important notes**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "Every shipment is different. Postage is based on **dimensional weight**."
            },
            {
              "text": "**ePacket*** is only available to approved contracted countries. Please see the **Shipping Options** FAQ for eligibility and restrictions."
            }
          ]
        }
      ]
    },
    {
      "id": "can-i-combine-shipment-requests-from-one-that-i-made-at-an-earlier-dat",
      "sourceIndex": 16,
      "question": "Can I combine shipment requests from one that I made at an earlier date?",
      "category": "shipping",
      "availability": "adapted",
      "baultNote": "Bault can merge an earlier shipment request into a later one while both still read 'requested'. Cancelling after a rate has been selected does carry a restocking fee, because by then the double-verification and packing have already been done.",
      "blocks": [
        {
          "kind": "p",
          "text": "Only if the shipment has not been started yet. Once a shipment has been **pulled and verified**, it cannot be combined with another request."
        },
        {
          "kind": "p",
          "text": "If your shipment still shows **“Requested”**, you can **add or remove items** before our team begins pulling it."
        },
        {
          "kind": "p",
          "text": "**Cancelled shipments (restocking fee): **A **$25 restocking fee** applies to cancelled shipments to help compensate for the **time and materials** used to **double verify and package** your shipment."
        }
      ]
    },
    {
      "id": "what-customs-value-is-declared-on-outgoing-packages",
      "sourceIndex": 17,
      "question": "What customs value is declared on outgoing packages?",
      "category": "shipping",
      "availability": "adapted",
      "baultNote": "Bault declares the value YOU entered, per item, on a commercial invoice — and never adjusts, reduces or omits it. Under-declaring to lower somebody's duty is customs fraud committed in their name. Import duty, VAT and brokerage are payable by the recipient.",
      "blocks": [
        {
          "kind": "p",
          "text": "The customs value declared on your outgoing package is the **customs value you enter** in your ShipMyCards shipment request. Since you do not buy the cards from us, we do not know what you paid for your cards. For **all international shipments**, a **declared customs value is required**."
        },
        {
          "kind": "p",
          "text": "ShipMyCards uses a **third-party insurance provider**, so you have the option to **insure your shipment (up to $5,000)** while still declaring a lower customs value."
        },
        {
          "kind": "p",
          "text": "**Disclaimer: **The collector is responsible for **all customs clearance**, **taxes**, **duties**, and **any charges related to the outgoing shipment**, including but not limited to **insurance**, **signature requirements**, **address changes**, **return postage**, and **any other carrier fees** charged by the selected carrier."
        }
      ]
    },
    {
      "id": "can-multiple-collectors-combine-shipments-to-save-on-postage",
      "sourceIndex": 18,
      "question": "Can Multiple collectors combine shipments to save on postage?",
      "category": "shipping",
      "availability": "adapted",
      "baultNote": "Bault supports this, modelled rather differently. Each collector keeps their own shipment with their own items and their own custody trail; a shipment GROUP records that they travel together and who pays the carrier. Joining is always the member's own act — nobody can be added to a group that would send their property to an address they never saw.",
      "blocks": [
        {
          "kind": "p",
          "text": "Yes, we do offer a group shipment option. Follow these steps to make sure that all collectors are shipped in the same package and make a quick easy process for everybody:"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "All Collectors make shipment request within the same day."
            },
            {
              "text": "All collectors type in the SAME name and address of where the shipment is going."
            },
            {
              "text": "All Collectors select “Group Shipment – place ALL collectors in comments” in the drop down shipping Option."
            },
            {
              "text": "All collector place everyone’s names in the Group in the Comment Box"
            }
          ]
        },
        {
          "kind": "p",
          "text": "All Group Shipments will be sent out FedEx for the Carrier Max Insurance for the combined shipment is 5K insurance."
        },
        {
          "kind": "p",
          "text": "The Group Shipment will not be held back if a single collector doesn’t make their shipment request prior to all shipments being pulled per workflow."
        }
      ]
    },
    {
      "id": "what-does-the-optional-insurance-cover",
      "sourceIndex": 19,
      "question": "What does the optional insurance cover?",
      "category": "shipping",
      "availability": "adapted",
      "baultNote": "Bault insures a parcel at 1.5% of the value you declare, with a $2 minimum and a $5,000 ceiling. Insuring above $500 forces a signature on delivery, because that is the condition the cover is written on. The specific terms quoted here are ShipMyCards'.",
      "blocks": [
        {
          "kind": "p",
          "text": "Optional insurance covers **loss, theft, or damage** that occurs during the **final shipment from ShipMyCards to your requested delivery address**."
        },
        {
          "kind": "p",
          "text": "**Signature requirement: **All packages insured **over $500** require a **signature**."
        },
        {
          "kind": "h",
          "level": 6,
          "text": "**What items can be insured?**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "We only insure **trading cards** through our service."
            },
            {
              "text": "For **non-card items**, please ask about insurance **before shipping**."
            }
          ]
        },
        {
          "kind": "p",
          "text": "**Not insurable through our service:** art prints, posters, framed items, and other large items."
        },
        {
          "kind": "p",
          "text": "**Insurance claims note: **For insurance claims, **damaged items and original packaging** may be required and may need to be returned **at your expense**."
        }
      ]
    },
    {
      "id": "what-is-the-gps-tracking-option-in-the-shipment-request",
      "sourceIndex": 20,
      "question": "What is the GPS tracking option in the Shipment request?",
      "category": "shipping",
      "availability": "adapted",
      "baultNote": "Bault offers a tracker in the parcel as a paid add-on, sold only alongside at least $500 of insurance — it exists to help recover a parcel somebody is going to claim on. The price and handover described here are ShipMyCards'.",
      "blocks": [
        {
          "kind": "p",
          "text": "ShipMyCards offers an optional **GPS tracking add-on** where we place an **Apple AirTag** inside your outgoing shipment so you can monitor its location while it’s in transit."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**How it works**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Cost: $30**"
            },
            {
              "text": "**Insurance requirement:** GPS tracking requires **insurance (minimum $500)**"
            }
          ]
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Tracking setup (Apple ID option)**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "If you enter your **Apple ID** when creating the shipment request, we’ll add it when your shipment ships so you can follow the tracking during transit."
            }
          ]
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**After delivery (AirTag transfer)**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "After your package arrives, you can submit a **helpdesk request** and we will remove the AirTag from the ShipMyCards Apple account so you can link it to **your own Apple device** for future use."
            },
            {
              "text": "If we don’t receive a helpdesk request, we will remove it from our account **2 weeks after delivery**."
            }
          ]
        },
        {
          "kind": "p",
          "text": "This option is compliant with **USPS and FedEx** regulations."
        }
      ]
    },
    {
      "id": "what-all-is-included-within-normal-processing",
      "sourceIndex": 21,
      "question": "What all is included within normal Processing?",
      "category": "intake",
      "availability": "adapted",
      "baultNote": "Bault's intake photographs each item, gives it a serial and a printed barcode, shelves it in a numbered location and publishes it to your vault, and storage is billed automatically after an included period. The included period and the fee are Bault's own, and they differ for oversized items.",
      "blocks": [
        {
          "kind": "p",
          "text": "Normal processing covers the standard steps ShipMyCards takes to receive, document, and store your items when they arrive."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**What we do during normal processing**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Daily mail pickup** from the post office"
            },
            {
              "text": "**Carefully open and document packages** (we photograph the package contents)"
            },
            {
              "text": "**Quick visual check** for any obvious shipping-related damage"
            },
            {
              "text": "**Upload photos to your online inventory** at ShipMyCards.com so you can manage your items remotely"
            },
            {
              "text": "[[**Secure storage**|https://www.shipmycards.com/services/collector-mailbox-and-vault-services/]] in a safe, insured environment"
            },
            {
              "text": "Your items are then ready for you to [[**ship, store, sell/trade, submit for grading, or send to consignment**|https://www.shipmycards.com/services/]] when you choose"
            }
          ]
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Optional upgraded services (additional charges may apply)**"
        },
        {
          "kind": "p",
          "text": "You can request additional services through your account, such as:"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "[[**Grading submissions**|https://www.shipmycards.com/services/psa-grading/]]"
            },
            {
              "text": "[[**Consignment partnerships & private sales**|https://www.shipmycards.com/services/consignment-options-private-sales/]]"
            },
            {
              "text": "[[**High-quality scans / better photos**|https://www.shipmycards.com/services/additional-assistance/]]"
            },
            {
              "text": "[[**Separating lots into individual items**|https://www.shipmycards.com/services/additional-assistance/]]"
            }
          ]
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Storage included + storage fees**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Cards:** The first **180 days** of storage are included. After 180 days, you will be charged **10% of the incoming item fee every 90 days**."
            },
            {
              "text": "**Large/oversized items:** Must be shipped home within **90 days**. If a large/oversized item remains in storage beyond 90 days, the **original incoming processing fee will be charged again**."
            }
          ]
        }
      ]
    },
    {
      "id": "how-long-after-delivery-do-items-get-uploaded-to-the-website",
      "sourceIndex": 22,
      "question": "How long after delivery do items get uploaded to the Website?",
      "category": "intake",
      "availability": "adapted",
      "baultNote": "Bault publishes a live figure rather than a target: your Inbound page shows how many parcels are waiting and how long the oldest unprocessed arrival has been waiting, taken from the actual queue. The turnaround stated here is ShipMyCards' commitment at their own facility.",
      "blocks": [
        {
          "kind": "p",
          "text": "Most items are uploaded to your ShipMyCards online inventory **within 1 business day** of arriving at our **Arizona** mailing address."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Check current intake status**"
        },
        {
          "kind": "p",
          "text": "You can view real-time progress by clicking the **Workflow** button in the left sidebar. This shows where our team is in both incoming and outgoing processing."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**A few important timing notes**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Arizona deliveries:** Usually processed and uploaded **within 1 business day** after delivery."
            },
            {
              "text": "**eBay delivery timestamps:** eBay may show delivery based on your local time vs **Arizona time**, which can make it look like delivery happened earlier than it did—often adding **8–12 hours** of confusion."
            },
            {
              "text": "**Oregon deliveries:** Items delivered to Oregon are **forwarded daily** and typically take **3–5 business days** to arrive in Arizona before they can be processed and uploaded."
            }
          ]
        }
      ]
    },
    {
      "id": "can-we-submit-a-card-for-grading-through-psa",
      "sourceIndex": 23,
      "question": "Can we submit a card for grading through PSA?",
      "category": "services",
      "availability": "adapted",
      "baultNote": "Bault supports third-party grading as a service request raised against a card in your vault, across five tiers, with a submission batch and a lifecycle state that stops a card being listed, sold or shipped while it is away at the grader. The tier prices and turnarounds quoted here are ShipMyCards'.",
      "blocks": [
        {
          "kind": "p",
          "text": "Yes. You can submit cards for **PSA grading through ShipMyCards** using the website. We handle **bulk group submissions** and send orders to PSA **weekly**."
        },
        {
          "kind": "h",
          "level": 6,
          "text": "**How to request PSA grading (website steps)**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "Log in to your ShipMyCards account"
            },
            {
              "text": "Go to your **Inventory**"
            },
            {
              "text": "Click **Action** button; from dropdown menu select “**Details”**"
            },
            {
              "text": "Select **“+Disposition”** link (found top right corner), select **“Submit to PSA grading”** from Disposition dropdown menu"
            },
            {
              "text": "Fill out required information and click **“Update”**"
            }
          ]
        },
        {
          "kind": "p",
          "text": "PSA current Pricing and options are updated in the Disposition menu at all times."
        },
        {
          "kind": "p",
          "text": "All Cards above $4,999 require a Walkthrough Service and would need prior approval."
        },
        {
          "kind": "p",
          "text": "**Store Credit Required: **You will not be able to submit actions like **grading, shipping, or selling** if you do not have enough **Store Credit** available in your account."
        },
        {
          "kind": "p",
          "text": "*By submitting cards for PSA grading through ShipMyCards, you grant ShipMyCards permission to photograph and/or video your cards for marketing and promotional use. Customer names, account details, and personal information will not be disclosed."
        },
        {
          "kind": "p",
          "text": "If you have concerns about your cards being used in marketing content, please contact our support team."
        },
        {
          "kind": "p",
          "text": "Step-by-step instructions can be found here:"
        },
        {
          "kind": "p",
          "text": "[[How to Submit Cards to PSA Grading Using Your ShipMyCards Account|https://www.blogger.com/blog/post/edit/4411785791571288916/2810393912431043110]]"
        },
        {
          "kind": "p",
          "text": "Prefer a YouTube Video. Check out our video tutorial:"
        },
        {
          "kind": "p",
          "text": "**[[How to Submit Cards to PSA Grading Using Your ShipMyCards Account|https://youtu.be/a1Cxm-qR66Y]]**"
        }
      ]
    },
    {
      "id": "what-consignment-options-do-you-offer",
      "sourceIndex": 24,
      "question": "What Consignment Options do you offer?",
      "category": "services",
      "availability": "adapted",
      "baultNote": "Bault supports consignment as a service request against a card, through three channel types — a card show, an auction house, or eBay through a partner seller — each with its own fee and deadline, plus an outright buyout option. The partners, splits and payout timings listed here are ShipMyCards'.",
      "blocks": [
        {
          "kind": "p",
          "text": "ShipMyCards offers multiple ways to sell your cards, from low-fee peer-to-peer sales to show and auction consignment. Options may vary based on card value, grading status, and current partner availability."
        },
        {
          "kind": "p",
          "text": "**1) Card Show Consignment –**We take your cards to local/advertised card shows and handle the selling for you."
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "You set the **asking price**, we do the rest"
            },
            {
              "text": "**Fee: 10%** (only if your card sells)"
            },
            {
              "text": "**Payout:** by **Monday after the show**"
            }
          ]
        },
        {
          "kind": "p",
          "text": "**2) PC Sports (eBay Auctions) – **Consign graded cards through PC Sports auctions at their terms/rates, plus ShipMyCards support."
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Fee:** PC Sports rates **+ 1%** to ShipMyCards"
            },
            {
              "text": "**Requirements: Graded cards only**, **$50 minimum**"
            },
            {
              "text": "**Payout:** credited to **Store Credit** after PC Sports pays (typically **6–10 weeks**)"
            },
            {
              "text": "ShipMyCards handles the **paperwork, accounting, and payout**"
            }
          ]
        },
        {
          "kind": "p",
          "text": "**3) Fanatics Collect- **Consign graded cards through Fanatics auctions at their terms/rates, plus ShipMyCards support."
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Fee:** Fanatic rates **+ 1%** to ShipMyCards"
            },
            {
              "text": "**Requirements: Graded cards only**, **$50 minimum**"
            },
            {
              "text": "**Payout:** credited to **Store Credit** after Fanatics Collect pays (typically **6–10 weeks**)"
            },
            {
              "text": "ShipMyCards handles the **paperwork, accounting, and payout**"
            }
          ]
        }
      ]
    },
    {
      "id": "how-do-i-request-a-higher-quality-scan-or-video-review",
      "sourceIndex": 25,
      "question": "How do I request a higher quality Scan or Video review?",
      "category": "services",
      "availability": "adapted",
      "baultNote": "Bault supports both as service requests against a card in your vault: professional photography, and a video review where an operator turns the card under a light and records what they find. Delivery is in the app, attached to the item, rather than through OneDrive.",
      "blocks": [
        {
          "kind": "p",
          "text": "You may request for a scan or video review on the website in the Disposition field in the Item Detail Screen. After completing the scan or video review we will provide a OneDrive Link where you can view the highest quality and download the scan/video if you want to save it for future use."
        }
      ]
    },
    {
      "id": "what-if-i-want-to-sell-or-grade-1-card-that-is-part-of-a-lot",
      "sourceIndex": 26,
      "question": "What if I want to Sell or Grade 1 card that is part of a lot?",
      "category": "services",
      "availability": "adapted",
      "baultNote": "Bault can break a lot into individually tracked items, each with its own serial, label, shelf and charge — and a lot of five or fewer cards is never created as a lot in the first place. The Disposition menu described here is ShipMyCards' interface.",
      "blocks": [
        {
          "kind": "p",
          "text": "If you need to sell or grade a single card from a lot, ShipMyCards makes it easy to separate that lot into individual items."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "How to separate a lot into individual items"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "Go to your **Inventory**"
            },
            {
              "text": "Click **Action** button; from dropdown menu select “**Details”**"
            },
            {
              "text": "Select **“+Disposition”** link (found top right corner), select **“Separate Lot into individual items” **from Disposition dropdown menu"
            }
          ]
        },
        {
          "kind": "p",
          "text": "Separating a lot will convert the pricing from the lot fee to the individual item fee. This option works best when you need to **sell or grade specific cards** from a lot."
        }
      ]
    },
    {
      "id": "what-if-i-need-help-with-looking-for-damage-on-a-card",
      "sourceIndex": 27,
      "question": "What if I need help with looking for damage on a card?",
      "category": "intake",
      "availability": "adapted",
      "baultNote": "Bault supports this as a condition inspection: a service request against a card in your vault where a person looks at the named areas and writes down what they find. Bault also records a condition grade at intake, and the arrival check on the parcel itself is recorded before any item exists.",
      "blocks": [
        {
          "kind": "p",
          "text": "During intake processing, ShipMyCards performs a **quick visual check** to confirm there’s no **obvious damage from shipping**. For a **closer, more detailed look**, the collector is responsible for reviewing the item photos and condition."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**What collectors should know about card condition**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "It’s important to review **clear photos and the seller’s description** before purchasing."
            },
            {
              "text": "If you are only looking for **Gem Mint** cards, we recommend buying **already graded cards**, since ShipMyCards does not determine the condition of every item processed."
            }
          ]
        },
        {
          "kind": "h",
          "level": 5,
          "text": "**Can I request a closer look?**"
        },
        {
          "kind": "p",
          "text": "Yes. If you need extra help, you can request:"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "A **better photo or scan **(available under the Disposition options)"
            },
            {
              "text": "A check for **specific damage** (corners, edges, surface, creases, etc.)"
            },
            {
              "text": "A **video review** (available under the Disposition options)"
            }
          ]
        }
      ]
    },
    {
      "id": "are-collectors-required-to-have-store-credit-to-use-the-service",
      "sourceIndex": 28,
      "question": "Are collectors required to have store credit to use the service?",
      "category": "fees",
      "availability": "adapted",
      "baultNote": "Bault does require a funded wallet: a negative balance blocks new shipments and service requests. Bault's own terms differ — a 14-day grace period, then interest at 0.05% per day, then an automatic suspension that still leaves the helpdesk open so you can settle. The 1% weekly figure here is ShipMyCards'.",
      "blocks": [
        {
          "kind": "p",
          "text": "Yes. **Store Credit is used to pay for incoming processing fees and shipping charges** on all items in your ShipMyCards account."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "What if my balance goes negative?"
        },
        {
          "kind": "p",
          "text": "Yes—accounts may go negative from time to time, and we understand that can happen. If you are actively sending items in, please **add Store Credit regularly**,** be responsible** with your balance, and k**eep your account in the positive.**"
        },
        {
          "kind": "h",
          "level": 5,
          "text": "Overdraft fee (weekly)"
        },
        {
          "kind": "p",
          "text": "If your account has been negative for **more than 14 days**, we charge a **weekly overdraft fee of 1% of the negative balance** until the balance is brought back positive."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "Account lockout"
        },
        {
          "kind": "p",
          "text": "Accounts will be locked if the balance is **more than $20 negative** (below **-$20**)."
        }
      ]
    },
    {
      "id": "can-i-cash-out-my-store-credit",
      "sourceIndex": 29,
      "question": "Can I cash out my Store Credit?",
      "category": "fees",
      "availability": "adapted",
      "baultNote": "Bault supports cashing out, with a published fee schedule quoted from the same figures that are charged, and a confirmation step. The fee schedule and the PayPal Friends & Family payout described here are ShipMyCards'.",
      "blocks": [
        {
          "kind": "p",
          "text": "Yes. You can cash out your ShipMyCards Store Credit using the **Cash Out Store Credit** link in the left menu bar. Cash outs are sent as **PayPal Friends & Family** payments."
        },
        {
          "kind": "h",
          "level": 5,
          "text": "Cash out fees"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "**Over $100: $5 + 1%**"
            },
            {
              "text": "**Under $100: 6%** (minimum fee **$0.99**)"
            }
          ]
        }
      ]
    },
    {
      "id": "can-i-send-an-international-shipment-to-my-shipmycards-address",
      "sourceIndex": 30,
      "question": "Can I send an International Shipment to my ShipMyCards address?",
      "category": "shipping",
      "availability": "adapted",
      "baultNote": "Bault accepts international arrivals at its U.S. addresses and flags them as such. The recipient of record clears customs and pays any duty, which is recorded on the parcel rather than left in a policy document.",
      "blocks": [
        {
          "kind": "p",
          "text": "**Yes.** You can send international packages to your ShipMyCards address."
        },
        {
          "kind": "p",
          "text": "**However, you (the recipient/importer) are responsible for:**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "Clearing **U.S. Customs**"
            },
            {
              "text": "Paying any **duties, tariffs, taxes**, and **carrier/brokerage fees**"
            },
            {
              "text": "Providing any information needed by the carrier/customs to release the package"
            }
          ]
        },
        {
          "kind": "p",
          "text": "**Important shipping notes:**"
        },
        {
          "kind": "ul",
          "items": [
            {
              "text": "Ask the sender to complete customs forms correctly:",
              "items": [
                "**HS / Tariff code for trading cards: 4911.99**",
                "**Country of origin: United States** (unless a different country of origin, i.e. Japanese trading cards)."
              ]
            }
          ]
        }
      ]
    }
  ]
};
