import { chromium } from 'playwright';
import { readFileSync } from 'node:fs';
const [,, svgPath, outPath, scale] = process.argv;
const svg = readFileSync(svgPath, 'utf8');
const browser = await chromium.launch();
const page = await browser.newPage({ deviceScaleFactor: Number(scale) || 3 });
await page.setContent(`<body style="margin:0">${svg}</body>`);
const el = await page.$('svg');
await el.screenshot({ path: outPath, omitBackground: false });
await browser.close();
console.log('wrote', outPath);
